// ItemOption.h: interface for the CItemOption class.
//
//////////////////////////////////////////////////////////////////////

#pragma once

#include "Item.h"
#include "User.h"

enum eOptionWings
{
	WINGS_ITEM_OPTION_ADD_PHYSI_DAMAGE = 80,
	WINGS_ITEM_OPTION_ADD_MAGIC_DAMAGE = 81,
	WINGS_ITEM_OPTION_ADD_DEFENSE_SUCCESS_RATE = 82,
	WINGS_ITEM_OPTION_ADD_DEFENSE = 83,
	WINGS_ITEM_OPTION_LUCK = 84,
	WINGS_ITEM_OPTION_ADD_HP_RECOVERY_RATE = 85,
	WINGS_ITEM_OPTION_ADD_HP_RECOVERY_RATE_ = 86,
	WINGS_ITEM_OPTION_MUL_HP = 87,
	WINGS_ITEM_OPTION_MUL_MP = 88,
	WINGS_ITEM_OPTION_ADD_DAMAGE_REDUCTION = 89,
	WINGS_ITEM_OPTION_ADD_DAMAGE_REFLECT = 90,
	WINGS_ITEM_OPTION_MUL_DEFENSE_SUCCESS_RATE = 91,
	WINGS_ITEM_OPTION_ADD_MONEY_AMOUNT_DROP_RATE = 92,
	WINGS_ITEM_OPTION_ADD_EXCELLENT_DAMAGE_RATE = 93,
	WINGS_ITEM_OPTION_ADD_PHYSI_DAMAGE_BY_LEVEL = 94,
	WINGS_ITEM_OPTION_MUL_PHYSI_DAMAGE = 95,
	WINGS_ITEM_OPTION_ADD_MAGIC_DAMAGE_BY_LEVEL = 96,
	WINGS_ITEM_OPTION_MUL_MAGIC_DAMAGE = 97,
	WINGS_ITEM_OPTION_ADD_SPEED_MAGIC = 98,
	WINGS_ITEM_OPTION_ADD_HUNT_HP = 99,
	WINGS_ITEM_OPTION_ADD_HUNT_MP = 100,
	WINGS_ITEM_OPTION_ADD_HP = 101,
	WINGS_ITEM_OPTION_ADD_MP = 102,
	WINGS_ITEM_OPTION_ADD_IGNORE_DEFENSE_RATE = 103,
	WINGS_ITEM_OPTION_ADD_BP = 104,
	WINGS_ITEM_OPTION_ADD_FULL_DAMAGE_REFLECT_RATE = 106,
	WINGS_ITEM_OPTION_MUL_DEFENSE = 105,
	WINGS_ITEM_OPTION_ADD_DEFENSIVE_FULL_HP_RESTORE_RATE = 107,
	WINGS_ITEM_OPTION_ADD_IGNORE_DEFENSE_RATE_ = 108,
	WINGS_ITEM_OPTION_ADD_FULL_DAMAGE_REFLECT_RATE_ = 109,
	WINGS_ITEM_OPTION_ADD_DEFENSIVE_FULL_HP_RESTORE_RATE_ = 110,
	WINGS_ITEM_OPTION_ADD_DEFENSIVE_FULL_MP_RESTORE_RATE = 111,
	WINGS_ITEM_OPTION_ADD_FULL_DAMAGE_REFLECT_RATE__ = 112,
	WINGS_ITEM_OPTION_ADD_CURSE_DAMAGE = 113,
	WINGS_ITEM_OPTION_LUCK_ = 114,
	WINGS_ITEM_OPTION_ADD_FULL_DAMAGE_REFLECT_RATE1_ = 115,
	WINGS_ITEM_OPTION_ADD_FULL_DAMAGE_REFLECT_RATE2_ = 116,
	WINGS_ITEM_OPTION_ADD_FULL_DAMAGE_REFLECT_RATE3_ = 117,
	WINGS_ITEM_OPTION_ADD_FULL_DAMAGE_REFLECT_RATE4_ = 118,
};

enum eItemOption
{
	ITEM_OPTION_ADD_PHYSI_DAMAGE = 80,
	ITEM_OPTION_ADD_MAGIC_DAMAGE = 81,
	ITEM_OPTION_ADD_DEFENSE_SUCCESS_RATE = 82,
	ITEM_OPTION_ADD_DEFENSE = 83,
	ITEM_OPTION_ADD_CRITICAL_DAMAGE_RATE = 84,
	ITEM_OPTION_ADD_HP_RECOVERY_RATE = 85,
	ITEM_OPTION_ADD_MONEY_AMOUNT_DROP_RATE = 86,
	ITEM_OPTION_MUL_DEFENSE_SUCCESS_RATE = 87,
	ITEM_OPTION_ADD_DAMAGE_REFLECT = 88,
	ITEM_OPTION_ADD_DAMAGE_REDUCTION = 89,
	ITEM_OPTION_MUL_MP = 90,
	ITEM_OPTION_MUL_HP = 91,
	ITEM_OPTION_ADD_EXCELLENT_DAMAGE_RATE = 92,
	ITEM_OPTION_ADD_PHYSI_DAMAGE_BY_LEVEL = 93,
	ITEM_OPTION_MUL_PHYSI_DAMAGE = 94,
	ITEM_OPTION_ADD_MAGIC_DAMAGE_BY_LEVEL = 95,
	ITEM_OPTION_MUL_MAGIC_DAMAGE = 96,
	ITEM_OPTION_ADD_SPEED = 97,
	ITEM_OPTION_ADD_HUNT_HP = 98,
	ITEM_OPTION_ADD_HUNT_MP = 99,
	ITEM_OPTION_ADD_WING_HP = 100,
	ITEM_OPTION_ADD_WING_MP = 101,
	ITEM_OPTION_ADD_IGNORE_DEFENSE_RATE = 102,
	ITEM_OPTION_ADD_BP = 103,
	ITEM_OPTION_MUL_BP = 104,
	ITEM_OPTION_ADD_WING_LEADERSHIP = 105,
	ITEM_OPTION_ADD_FENRIR1 = 106,
	ITEM_OPTION_ADD_FENRIR2 = 107,
	ITEM_OPTION_ADD_FENRIR3 = 108,
	ITEM_OPTION_ADD_FULL_DAMAGE_REFLECT_RATE = 109,
	ITEM_OPTION_ADD_DEFENSIVE_FULL_HP_RESTORE_RATE = 110,
	ITEM_OPTION_ADD_DEFENSIVE_FULL_MP_RESTORE_RATE = 111,
	ITEM_OPTION_ADD_DINORANT1 = 112,
	ITEM_OPTION_ADD_CURSE_DAMAGE = 113,
	ITEM_OPTION_ADD_CURSE_DAMAGE_BY_LEVEL = 114,
	ITEM_OPTION_MUL_CURSE_DAMAGE = 115,
	ITEM_OPTION_ADD_DOUBLE_DAMAGE_RATE = 116,
	ITEM_OPTION_ADD_EXPERIENCE_RATE = 117,
	ITEM_OPTION_ADD_COMBO_EXPERIENCE_RATE = 118,
	ITEM_OPTION_ADD_HP = 119,
	ITEM_OPTION_ADD_MP = 120,
	ITEM_OPTION_ADD_HP_BY_LEVEL = 121,
	ITEM_OPTION_ADD_MP_BY_LEVEL = 122,
	ITEM_OPTION_ADD_DAMAGE = 123,
	ITEM_OPTION_ADD_DAMAGE_BY_LEVEL = 124,
	ITEM_OPTION_MUL_DAMAGE = 125,
	ITEM_OPTION_ADD_DEFENSE_BY_LEVEL = 126,
	ITEM_OPTION_MUL_DEFENSE = 127,
};

struct ITEM_OPTION_INFO
{
	int Index;
	int OptionIndex;
	int OptionValue;
	int ItemMinIndex;
	int ItemMaxIndex;
	int ItemOption1;
	int ItemOption2;
	int ItemOption3;
	int ItemNewOption;
};

typedef std::map<int, std::vector<ITEM_OPTION_INFO>> type_map_option;

class CItemOption
{
public:
	CItemOption();
	virtual ~CItemOption();
	void Load(char* path);
	void ExportXML(std::string filename);

	bool GetItemOption(int index, CItem* lpItem);
	void CalcItemCommonOption(LPOBJ lpObj, bool flag);
	void InsertOption(LPOBJ lpObj, CItem* lpItem, bool flag);
	void AddOption(LPOBJ lpObj, int index, int value, CItem* lpItem, bool flag);
private:
	type_map_option m_ItemOptionInfo;
};

extern CItemOption gItemOption;
