[MainInfo]
ClientName = Main.exe
MaxOfInstance = 2
PluginAntiHack = 
PluginReShader = 
PathExport = ..\Client_2

[HelperInfo]
;==================================================
; Cấu hình level kích hoạt MuHelper
;==================================================
HelperActiveAlert = 0
HelperActiveLevel = 80

[ReconnectInfo]
;==================================================
; Hệ thống tự động kết nối lại
; ReconnectTime = 0 (Tắt)
;==================================================
ReconnectTime = 300000

[CharacterInfo]
;==================================================
; Tốc độ tối đa dựa trên điểm nhanh nhẹn (Agility) của nhân vật
;==================================================
DWMaxAttackSpeed = 67000
DKMaxAttackSpeed = 65000
FEMaxAttackSpeed = 67000
MGMaxAttackSpeed = 67000
DLMaxAttackSpeed = 67000
SUMaxAttackSpeed = 67000
RFMaxAttackSpeed = 67000

[Custom]
;==================================================
; Vị trí logo khi chụp ảnh màn hình
; Logo: Data\Interface\HUD\MU-logo.OZT
; 0: Tắt
; 1: Vị trí trên bên trái
; 2: Vị trí trên bên phải
; 3: Vị trí dưới bên trái
; 4: Vị trí dưới bên phải
; 5: Vị trí trung tâm
;==================================================
PrintLogo = 4

;==================================================
; Loại bỏ nhân vật trong màn hình tạo nhân vật
; 0: Bình thường (Không xóa)
; 1: Xóa Summoner/DarkLord/RageFighter
; 2: Xóa Summoner/RageFighter
; 3: Xóa RageFighter
;==================================================
RemoveClass = 0

;==================================================
; Thiết lập chất lượng FPS
; FpsRenderMax: Giới hạn mức giảm FPS tối đa
; FpsWindowsOption: Bật hỏi số FPS khi vào game (Bật:1/Tắt:0)
;==================================================
FpsRenderMax = 120
FpsWindowsOption = 0

;==================================================
; Hiển thị logo guild của nhân vật trong khi chat
; 0: Tắt
; 1: Bật
;==================================================
RenderGuildLogo = 1

;==================================================
; Nhập số cấp độ ép đồ tối đa
; Cấp tối đa: 10 ~ 15
; - Mix tối đa lên cấp 10
; - Mix tối đa lên cấp 11
; - Mix tối đa lên cấp 12
; - Mix tối đa lên cấp 13
; - Mix tối đa lên cấp 14
; - Mix tối đa lên cấp 15
;==================================================
MaxItemLevelOn = 10

;==================================================
; Bật hoặc tắt hệ thống (mix) cánh
; Cánh cấp 3 của nhiệm vụ thứ 3 cho người chơi
; - Pha trộn (Mix) Feather Of Condor
; - Pha trộn (Mix) Cánh cấp 3
;==================================================
ShutdownLevelWing3 = 1

;==================================================
; Kích hoạt tính năng giao dịch bằng coin
; - 0: Tắt
; - 1: Bật
;==================================================
EnableTradeCoin = 1

;==================================================
; Kích hoạt tính năng ghi nhớ tài khoản
; - 0: Tắt
; - 1: Bật
;==================================================
EnableRememberAccount = 1

;==================================================
; Bật ngân hàng ngọc
; - 0: Tắt
; - 1: Bật
;==================================================
EnableJewelOfInventory = 1

;==================================================
; Kích hoạt cửa sổ Thông tin Reset
; - 0: Tắt
; - 1: Bật
;==================================================
EnableWindowsResetInfo = 1

;==================================================
; Bật kỹ năng Castle Siege trên tất cả bản đồ
; Bạn cũng cần bật nó trong Common.data của máy chủ
; 1: Kích hoạt trên tất cả bản đồ
; 0: Chỉ kích hoạt trong Castle Siege
;==================================================
EnableCsSkillsAllMaps = 1

;==================================================
; Cài đặt chế độ hiển thị cho cấp bậc người dùng (RankUserSwitch)
; 0: Hiển thị đầy đủ
; 1: Ẩn thông số thống kê
; 2: Ẩn logo
; 3: Ẩn cả thông số thống kê và logo
; 4: Hiển thị logo phía trên đầu
; 5: Gỡ bỏ (Vô hiệu hóa)
;==================================================
RankUserSwitch = 0
RankUserShowOverHead = 1
RankUserOnlyOnSafeZone = 1
RankUserShowReset = 1
RankUserShowMasterReset = 1
RankUserNeedAltKey = 0

;==================================================
; Kiểu hiển thị HP tổ đội (Render Hp Party Type)
; 0: Bình thường
; 1: Dạng biểu tượng (Icon)
; 2: Tắt hiển thị
;==================================================
PartyHpBarType = 1

;==================================================
; Bật/Tắt nút Menu
; Cài đặt (CustomMenuSwitch)
; 0: Tắt
; 1: Bật
; Cài đặt (CustomMenuType)
; 1: Dạng texture logo
; 2: Dạng nút (Button) cạnh MuHelper
;==================================================
CustomMenuSwitch = 1
CustomMenuType = 2
EnableVipShopButton = 1
EnableRankingButton = 1
EnableCommandButton = 1
EnableOptionButton = 1
EnableEventTimeButton = 1

;==================================================
; Bật/Tắt giao diện Windows tùy chỉnh (Enable Windows Custom)
; 0: Tắt
; 1: Bật
;==================================================
EnableWindowsVipShop = 1
EnableWindowsRankTop = 1
EnableWindowsCommand = 1
EnableWindowsEventTime = 1

;==================================================
; - Chế độ cửa hàng cá nhân (SwitchPersonalShopType)
; 0: Thường
; 1: Cao cấp (Premium)

; - Bật/Tắt nút cửa hàng tùy chỉnh (chỉ áp dụng khi PersonalShopType = 0)
; 0: Tắt
; 1: Bật
;==================================================
SwitchPersonalShopType = 1
EnableOffStoreButtom = 1
EnableStoreBlessButtom = 1
EnableStoreSoulButtom = 1
EnableStoreChaosButtom = 1
EnableStoreCoin1Buttom = 1
EnableStoreCoin2Buttom = 1
EnableStoreCoin3Buttom = 1

;==================================================
; Cảnh hiển thị trong game (Scene Render InGame)
; 0: Bình thường         -> [Đăng nhập: World74][Nhân vật: World75]
; 1: Hạ cấp S1
; 2: Hạ cấp S2/S3        -> [Đăng nhập: World56][Nhân vật: World55]
; 3: Hạ cấp S4           -> [Đăng nhập: World78][Nhân vật: World79]
; 4: Nâng cấp (S13)      -> [Đăng nhập: World95][Nhân vật: World94]
;==================================================
SceneLogin = 1
SceneCharacter = 1

[Interface]
;==================================================
; Lấy tên máy chủ từ ServerList.bmd hoặc từ ConnectServer trong ServerList
; 0: Từ ConnectServer
; 1: Từ file ServerList.bmd
;==================================================
ServerDefaultName = 0

;==================================================
; Hệ thống kích thước và thay đổi kích thước màn hình
; 0: Bình thường
; 1: Mở rộng chiều cao màn hình rộng (widescreen height)
; 2: Mở rộng toàn bộ kích thước màn hình rộng (full widescreen)
;==================================================
ScreenType = 2

;==================================================
; Thay đổi giao diện Game
; 0: Gốc SS6
; 1: Hậ cấp S1    -> (Req: HUD/Look-1/)
; 2: Hậ cấp s2/s3 -> (Req: HUD/Look-2/)
; 3: Ex700 (s16)  -> (Req: HUD/Look-3/)
; 4: Legends      -> (Req: HUD/Look-4/)
;==================================================
LookAndFeel = 1

;==================================================
; Hiển thị thông tin nhân vật màn hình chọn nhân vật (Char Info Balloon - ở màn hình chọn nhân vật)
; 0: Bình thường
; 1: Hiển thị số lần Reset -> (Yêu cầu: file character_ex(1).ozt)
; 2: Hiển thị số lần Reset + Master Reset -> (Yêu cầu: file character_ex(2).ozt)
;==================================================
CharInfo = 2

;==================================================
; Biểu cảm trò chuyện tùy chỉnh (Custom chat emoticon)
; 0: Tắt
; 1: Bật biểu cảm -> (yêu cầu: file newui_chat_back.OZJ)
; 2: Chặn chức năng chat riêng (Wissper) -> (yêu cầu: file newui_chat_back.OZJ)
; 3: Bật biểu cảm + Chặn chat riêng -> (yêu cầu: file newui_chat_back.OZJ)
;==================================================
ChatEmoticon = 3

;==================================================
; Kiểu chữ thông báo khi nhặt đồ
; 0: Gốc - Thông báo ở khung Exp
; 1: Thông báo kiểu chữ vàng GM chat
;==================================================
PickItemTextType = 1

;==================================================
; Mở rộng hành trang (Inventory Extension)
; 1: Bật
; 0: Tắt
; Tối đa: MaxInventoryExtension = 4
;==================================================
InventoryExtension = 1
MaxInventoryExtension = 4

;==================================================
; Mở rộng kho đồ (WareHouse Extension)
; 1: Bật
; 0: Tắt
;==================================================
WareHouseExtension = 1

;==================================================
; Giao diện Cash Shop trong game (Interface CashShop InGame)
; 1: Bật
; 0: Tắt
;==================================================
CashShopInGame = 1

;==================================================
; Giao diện MuHelper (hỗ trợ tự động trong game)
; 1: Bật
; 0: Tắt
;==================================================
OficialMuHelper = 1

;==================================================
; Giao diện Cây Kỹ Năng Master (Master Skill Tree)
; 1: Bật
; 0: Tắt
;==================================================
MasterSkill = 1

;==================================================
; Giao diện hiển thị Thời gian Xâm Lược và Số Quái Đã Tiêu Diệt (Time Invasion và MonsterKill)
; 1: Bật
; 0: Tắt
;==================================================
InvasionInfoTime = 1

;==================================================
; Giao diện SS18
; 1: Enable
; 0: Disable
;==================================================
RenderItemToolip = 1
RenderItemNameDrop = 1
RenderCharacterName = 1
RenderEquipmentEarring = 1
RenderEquipmentFlagNat = 1
RenderEquipmentCostume = 1
RenderEquipmentPetMuun = 1
RenderEquipmentPetEagle = 1
